### ISSUE TITLE
Tests possibly fail

### ISSUE THREAD

**Issue by sunoru** [andreasnoack/RNGTest.jl#6]
I got this info when running a test just now, and it sometimes occurs:

ERROR: LoadError: LoadError: test failed: 0.000874804346016389 > 0.001
 in expression: (RNGTest.sstring_HammingIndep(f,1,500000,20,10,300,0))[:Mean] > pval
 in default_handler at test.jl:30
 in do_test at test.jl:53

**Comment by andreasnoack** [comment]
Can you provide a little more info. Are you just running `Pkg.test("RNGTest")` with the standard Julia setup? Or are you testing a custom RNG? What is `versioninfo()`?

**Comment by sunoru** [comment]
I use `Pkg.test("RNGTest")`, and my `versioninfo()` shows:

Julia Version 0.4.3
Commit a2f713d* (2016-01-12 21:37 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblasp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by andreasnoack** [comment]
How often do you see the error? Every time, 1/10th of the time?

**Comment by andreasnoack** [comment]
...and what about `Pkg.status("RNG")`?

**Comment by sunoru** [comment]
I cloned the RNGTest package from the source manually.

I tried to test `RNGTest.sstring_HammingIndep(rand, 1, 500000, 20, 10, 300, 0)[:Mean] > 0.01` for about 150 times, 3 failed.

**Comment by andreasnoack** [comment]
In the first post you tested with `0.001` and in the last you used `0.01`? Which is correct? The p-values should be uniformly distributed under the null, so you'd expect test failure with the same frequency as your significance level. With `0.01` I don't think it is unlikely to see 3 failures in 150 trials.

**Comment by sunoru** [comment]
oh sorry I used 0.01 by mistake.. The original failure is with 0.001

So there is always a small probability?

**Comment by andreasnoack** [comment]
Yes. Under the null the probability of failure is exactly equal to the number you are using for the test.
