### ISSUE TITLE
Binary dependency for Windows?

### ISSUE THREAD

**Issue by GregPlowman** [andreasnoack/RNGTest.jl#9]
I'd like to use this package on Windows.
Unfortunately I don't have the required environment setup to build the dependencies.
Would it be possible to provide a pre-compiled binary for Windows users?

**Comment by andreasnoack** [comment]
Unfortunately, I don't really have the bandwidth to figure out how to supply binaries right now. A pull request would be great if you can figure out to do setup a system with binaries.

**Comment by andreasnoack** [comment]
@GregPlowman Exciting news here. Our infrastructure for binaries has improved a lot and I just got the Windows binaries working. I'll tag a new release right away.

**Comment by GregPlowman** [comment]
Exciting news indeed!
Thanks so much for this.
